version: '3.8'

services:
  ponto-api:
    image: pontonow-backend:latest
    networks:
      - echonet
    environment:
      - APP_NAME=PontoNow
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=ponto
      - DB_USERNAME=root
      - DB_PASSWORD=Akio2604*
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ponto-api.rule=Host(`apiponto.echo.dev.br`)"
        - "traefik.http.routers.ponto-api.entrypoints=websecure"
        - "traefik.http.routers.ponto-api.tls.certresolver=myresolver"
        - "traefik.http.services.ponto-api.loadbalancer.server.port=9000"

  ponto-web:
    image: pontonow-frontend:latest
    networks:
      - echonet
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ponto-web.rule=Host(`ponto.echo.dev.br`)"
        - "traefik.http.routers.ponto-web.entrypoints=websecure"
        - "traefik.http.routers.ponto-web.tls.certresolver=myresolver"
        - "traefik.http.services.ponto-web.loadbalancer.server.port=80"

networks:
  echonet:
    external: true
